## KLIMATA ILOILO DATA PREPROCESSING (STANDARDIZATION STAGE)

### We also standardized the datasets to make sure all the indicators are on the same scale before combining or comparing them. We start with amenity.

## Importing essential libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

### Importing CSV file for Amenity data

In [3]:
AME_DATA = pd.read_csv('AMENITY_FINAL.csv')

### Viewing Amenity Dataframe's first 5 rows

In [4]:
AME_DATA.head()

,uuid,adm4_pcode,date,college_nearest,community_centre_nearest,school_nearest,shelter_nearest,town_hall_nearest,university_nearest,location1.adm4_en,location1.brgy_total_area
0,osmpa001e83,ph063022075,2022-01-01,499.693700,363.721118,196.962495,396.840748,0.000000,457.790233,delgado-jalandoni-bagumbayan,0.0235
1,osmpa001cac,ph063022085,2022-01-01,190.538945,294.050675,0.000000,755.295238,524.007659,348.098929,laguda,0.0537
2,osmpa001cab,ph063022132,2022-01-01,249.824455,554.323482,212.821448,600.801916,79.373668,1151.978301,progreso-lapuz,0.2741
3,osmpa001caa,ph063022092,2022-01-01,554.897237,553.326752,238.790126,1168.852374,0.000000,1370.429642,libertad-lapuz,0.0383
4,osmpa001ca9,ph063022054,2022-01-01,11.836872,332.472393,0.000000,396.790167,309.502693,988.501036,edganzon,0.1033

### Standardizing Amenity columns

In [5]:
from sklearn.preprocessing import StandardScaler

cols_to_standardize = cols_to_standardize = [
    'college_nearest',
    'community_centre_nearest',
    'school_nearest',
    'shelter_nearest',
    'town_hall_nearest',
    'university_nearest'
]

scaler = StandardScaler()

AME_Sta = AME_DATA.copy()
AME_Sta[cols_to_standardize] = scaler.fit_transform(AME_Sta[cols_to_standardize])

AME_Sta.head()

,uuid,adm4_pcode,date,college_nearest,community_centre_nearest,school_nearest,shelter_nearest,town_hall_nearest,university_nearest,location1.adm4_en,location1.brgy_total_area
0,osmpa001e83,ph063022075,2022-01-01,-0.671659,-0.745288,-0.042481,-1.108379,-0.997424,-0.802596,delgado-jalandoni-bagumbayan,0.0235
1,osmpa001cac,ph063022085,2022-01-01,-0.907662,-0.771310,-0.743222,-0.862537,-0.528983,-0.885474,laguda,0.0537
2,osmpa001cab,ph063022132,2022-01-01,-0.862404,-0.674097,0.013941,-0.968495,-0.926467,-0.278095,progreso-lapuz,0.2741
3,osmpa001caa,ph063022092,2022-01-01,-0.629517,-0.674470,0.106331,-0.578905,-0.997424,-0.113042,libertad-lapuz,0.0383
4,osmpa001ca9,ph063022054,2022-01-01,-1.044080,-0.756960,-0.743222,-1.108413,-0.720741,-0.401612,edganzon,0.1033

### Saves standardized Amenity dataframe to csv.

In [6]:
AME_Sta.to_csv("AMENITY_STANDARDIZED.csv", index=False)