# KLIMATA ILOILO - POPULATION MAP with docstrings

In [2]:
import pandas as pd
import numpy as np

In [5]:
pop_df = pd.read_csv(r"C:\Users\Value Lines\Documents\FINAL_DATASETS\POPULATION_FINAL.csv")

In [6]:
pop_df.head()

,uuid,adm4_pcode,date,pop_count_total,pop_count_mean,pop_count_median,pop_count_stdev,pop_count_min,pop_count_max,adm4_en,brgy_total_area
0,wdpop000001,ph063022152,2000-01-01,1492.030518,14.346447,14.088117,9.941083,1.157729,39.577888,hibao-an norte,0.8800
1,wdpop000002,ph063022015,2000-01-01,688.092651,45.872843,46.660271,6.994909,30.479767,55.304688,bantud,0.1261
2,wdpop000003,ph063022118,2000-01-01,1734.744507,133.441885,18.758980,247.449747,11.151038,968.687927,north baluarte,0.1259
3,wdpop000018,ph063022040,2000-01-01,1891.350830,61.011317,60.119343,28.049733,17.409624,128.819382,cuartero,0.2656
4,wdpop000019,ph063022020,2000-01-01,2018.401123,288.343018,268.530884,124.519965,130.097717,472.024048,monica blumentritt,0.0626

In [148]:
pop_df['date'] = pd.to_datetime(pop_df['date'])

latest_date = pop_df['date'].max()

latest_rows = pop_df[pop_df['date'] == latest_date]

print(latest_rows)

             uuid   adm4_pcode       date  pop_count_total  pop_count_mean  \
3600  wdpop0044ae  ph063022118 2020-01-01      1997.376953      153.644381
3601  wdpop0044af  ph063022015 2020-01-01       785.250183       52.350012
3602  wdpop0044b0  ph063022110 2020-01-01      9717.523438      323.917448
3603  wdpop0044b1  ph063022040 2020-01-01      2016.500732       65.048411
3604  wdpop0044b2  ph063022020 2020-01-01      2118.273438      302.610491
...           ...          ...        ...              ...             ...
3775  wdpop0047dc  ph063022101 2020-01-01       879.203491       79.927590
3776  wdpop0047dd  ph063022087 2020-01-01      3698.088867      108.767320
3777  wdpop0047de  ph063022173 2020-01-01      1280.655029       60.983573
3778  wdpop0047df  ph063022129 2020-01-01      1123.179932      140.397491
3779  wdpop0047e0  ph063022019 2020-01-01      5931.465820       30.893051

      pop_count_median  pop_count_stdev  pop_count_min  pop_count_max  \
3600         26.973276       288.041872       9.792673    1129.023682
3601         52.382965        11.724451      31.649677      76.538689
3602        268.267914       200.023861      10.259146     680.106323
3603         64.598114        28.236092      22.269819     134.651764
3604        338.808258       150.454537     101.218414     502.019318
...                ...              ...            ...            ...
3775         89.942368        24.598965      38.594624     121.763069
3776         91.476242        63.437714      50.158844     352.771179
3777         59.307278        16.329618      29.317209      92.967323
3778        162.409073        53.262405      47.576363     194.666199
3779         24.234859        19.571695       6.617217      96.899879

                 adm4_en  brgy_total_area
3600      north baluarte           0.1259
3601              bantud           0.1261
3602      molo boulevard           0.2428
3603            cuartero           0.2656
3604  monica blumentritt           0.0626
...                  ...              ...
3775             magdalo           0.1045
3776         lapuz norte           0.3448
3777      south san jose           0.2666
3778      poblacion molo           0.0660
3779             bito-on           1.6052

[180 rows x 11 columns]

In [150]:
top5_pop = latest_rows.sort_values(by='pop_count_total', ascending=True).head(20)
print(top5_pop)

             uuid   adm4_pcode       date  pop_count_total  pop_count_mean  \
3706  wdpop004717  ph063022075 2020-01-01       153.710114      153.710114
3628  wdpop0044d9  ph063022085 2020-01-01       170.798279       28.466380
3722  wdpop004790  ph063022034 2020-01-01       180.185776       90.092888
3640  wdpop0045c2  ph063022081 2020-01-01       252.623764       50.524753
3732  wdpop00479a  ph063022053 2020-01-01       255.837372       36.548196
3766  wdpop0047bf  ph063022193 2020-01-01       270.737152       54.147430
3771  wdpop0047c7  ph063022076 2020-01-01       311.385223      103.795074
3676  wdpop00462c  ph063022093 2020-01-01       350.444031       70.088806
3613  wdpop0044ca  ph063022150 2020-01-01       371.315491       33.755954
3767  wdpop0047c0  ph063022078 2020-01-01       391.609131       78.321826
3762  wdpop0047bb  ph063022028 2020-01-01       442.185974      110.546494
3710  wdpop00471b  ph063022185 2020-01-01       467.661652      155.887217
3659  wdpop0045ef  ph063022161 2020-01-01       478.710388       79.785065
3644  wdpop0045d8  ph063022097 2020-01-01       481.492676      120.373169
3689  wdpop004683  ph063022070 2020-01-01       494.003845       35.285989
3655  wdpop0045eb  ph063022181 2020-01-01       504.332520       63.041565
3682  wdpop00464d  ph063022091 2020-01-01       520.351929       86.725321
3711  wdpop00471c  ph063022146 2020-01-01       522.081787       34.805452
3649  wdpop0045e4  ph063022045 2020-01-01       524.151611      174.717204
3707  wdpop004718  ph063022057 2020-01-01       529.019531      176.339844

      pop_count_median  pop_count_stdev  pop_count_min  pop_count_max  \
3706        153.710114         0.000000     153.710114     153.710114
3628         25.113842        11.814809      16.949263      52.122669
3722         90.092888         4.521706      85.571182      94.614594
3640         19.536352        48.768500      16.692966     144.338913
3732         20.407116        32.045250      13.666192     113.089890
3766         52.371300         8.701972      45.921799      69.675346
3771        113.250648        20.510491      75.319351     122.815224
3676         74.930328        11.799705      46.693703      77.863693
3613         26.145834        22.436976      16.262806      89.396606
3767         37.814682        58.549943      24.153801     163.536316
3762        121.288956        34.980397      56.868088     142.740005
3710        159.956039        32.021752     114.792946     192.912659
3659         80.125549         2.252500      77.061348      82.865089
3644        125.541641        58.927536      46.364811     184.044601
3689         34.936138        19.117044      12.560597      58.627476
3655         61.114334        13.423987      44.249222      83.130112
3682         86.223152        31.672736      49.126312     146.643967
3711         31.693810        12.912477      16.505907      64.564323
3649        169.870682         7.970683     168.326767     185.954147
3707        138.662537        58.418763     131.503967     258.852997

                             adm4_en  brgy_total_area
3706    delgado-jalandoni-bagumbayan           0.0235
3628                          laguda           0.0537
3722  el 98 castilla (claudio lopez)           0.0161
3640                       kauswagan           0.0434
3732                     east timawa           0.0647
3766                     yulo-arroyo           0.0373
3771                       javellana           0.0294
3676              lopez jaena (jaro)           0.0480
3613                       san felix           0.0974
3767                       calubihan           0.0345
3762    seminario (burgos jalandoni)           0.0489
3710                  timawa tanza i           0.0181
3659                       san roque           0.0545
3644                     luna (jaro)           0.0387
3689                           inday           0.1466
3655                          tap-oc           0.0601
3682          libertad, santa isabel           0.0458
3711                      sampaguita           0.1348
3649                    desamparados           0.0271
3707                          flores           0.0383

In [8]:
latest_rows.head()

,uuid,adm4_pcode,date,pop_count_total,pop_count_mean,pop_count_median,pop_count_stdev,pop_count_min,pop_count_max,adm4_en,brgy_total_area
3600,wdpop0044ae,ph063022118,2020-01-01,1997.376953,153.644381,26.973276,288.041872,9.792673,1129.023682,north baluarte,0.1259
3601,wdpop0044af,ph063022015,2020-01-01,785.250183,52.350012,52.382965,11.724451,31.649677,76.538689,bantud,0.1261
3602,wdpop0044b0,ph063022110,2020-01-01,9717.523438,323.917448,268.267914,200.023861,10.259146,680.106323,molo boulevard,0.2428
3603,wdpop0044b1,ph063022040,2020-01-01,2016.500732,65.048411,64.598114,28.236092,22.269819,134.651764,cuartero,0.2656
3604,wdpop0044b2,ph063022020,2020-01-01,2118.273438,302.610491,338.808258,150.454537,101.218414,502.019318,monica blumentritt,0.0626

In [10]:
latest_rows = latest_rows.drop(columns=[
    "uuid",
    "pop_count_mean",
    "pop_count_median",
    "pop_count_stdev",
    "pop_count_min",
    "pop_count_max"
])

In [13]:
latest_rows.to_csv("POP_LATEST.csv", index=False)

In [14]:
df = pd.read_csv("BRGY_STANDARDIZED.csv")

In [15]:
df = df.drop(columns=['uuid'])

In [16]:
df['adm4_pcode'] = df['adm4_pcode'].str.lower()

In [17]:
merge_df = pd.merge(df, latest_rows, on="adm4_pcode", how="inner")

In [21]:
merge_df = merge_df.drop(columns = [
    "date_x",
    "freq",
    "brgy_total_area_x",
    "brgy_distance_to_coast",
    "brgy_is_coastal"
])

In [22]:
from shapely import wkt

def safe_load_wkt(value):
    try:
        if pd.isna(value) or not value.strip():
            return None
        return wkt.loads(value)
    except Exception:
        return None  # Skip invalid geometry strings

merge_df["geometry"] = merge_df["geometry"].apply(safe_load_wkt)

In [23]:
merge_df = merge_df[merge_df["geometry"].notnull()]

In [24]:
import pandas as pd
import geopandas as gpd

# Convert to GeoDataFrame
gdf = gpd.GeoDataFrame(merge_df, geometry="geometry", crs="EPSG:4326")

# Extract boundary coordinates for each polygon
def extract_coords(poly):
    return list(poly.exterior.coords)

gdf["boundary_coords"] = gdf["geometry"].apply(extract_coords)

rows = []
for _, row in gdf.iterrows():
    for lon, lat in row["boundary_coords"]:
        # Copy all columns from the current row
        record = row.to_dict()
        # Replace geometry with coordinates
        record["longitude"] = lon
        record["latitude"] = lat
        # Optional: remove the polygon geometry and coords list (to avoid very large CSV)
        record.pop("geometry", None)
        record.pop("boundary_coords", None)
        rows.append(record)

# Convert to DataFrame
coords_df = pd.DataFrame(rows)

# Save as CSV
coords_df.to_csv("pop_polys.csv", index=False)

In [32]:
coords_df.head()

,adm4_pcode,location.adm4_en,date_y,pop_count_total,adm4_en,brgy_total_area_y,longitude,latitude
0,ph063022084,Our Lady Of Fatima,2020-01-01,3379.26123,our lady of fatima,0.1906,122.564165,10.720568
1,ph063022084,Our Lady Of Fatima,2020-01-01,3379.26123,our lady of fatima,0.1906,122.564713,10.720606
2,ph063022084,Our Lady Of Fatima,2020-01-01,3379.26123,our lady of fatima,0.1906,122.565234,10.720176
3,ph063022084,Our Lady Of Fatima,2020-01-01,3379.26123,our lady of fatima,0.1906,122.564826,10.719670
4,ph063022084,Our Lady Of Fatima,2020-01-01,3379.26123,our lady of fatima,0.1906,122.564232,10.718980

In [36]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Polygon

# --- Load CSV ---
poly_df = pd.read_csv("pop_polys.csv")

# --- Clean column names (GeoJSON-safe) ---
poly_df.columns = poly_df.columns.str.replace(r"[^0-9a-zA-Z_]+", "_", regex=True)

# --- Keep only desired columns (only keep ones that exist) ---
keep_cols = [
    "adm4_pcode",
    "location_adm4_en",
    "date_y",
    "pop_count_total",
    "adm4_en",
    "brgy_total_area_y",
    "longitude",
    "latitude"
]

# Filter only columns that actually exist in the file
existing_cols = [c for c in keep_cols if c in poly_df.columns]
poly_df = poly_df[existing_cols].copy()

# --- Add risk columns (if missing) ---
for col in ['risk_level', 'risk_label']:
    if col not in poly_df.columns:
        poly_df[col] = None  # create blank column
    poly_df[col] = poly_df[col].astype(str)

# --- Convert barangay points to polygons ---
records = []
for code, group in poly_df.groupby("adm4_pcode"):
    # group all coordinate pairs
    coords = list(zip(group["longitude"], group["latitude"]))
    if len(coords) > 2:  # valid polygon requires at least 3 points
        row = group.iloc[0].copy()
        row["geometry"] = Polygon(coords)
        records.append(row)
    else:
        print(f"⚠️ Skipped {code}: not enough points to form polygon")

# --- Create GeoDataFrame ---
if records:
    gdf = gpd.GeoDataFrame(records, crs="EPSG:4326")
    
    # --- Save as GeoJSON ---
    gdf.to_file("iloilo_pop.geojson", driver="GeoJSON")

    print("✅ GeoJSON successfully saved with these columns:")
    print(gdf.columns.tolist())
    print(f"Total barangays exported: {len(gdf)}")

else:
    print("❌ No valid polygons were created. Check if your CSV has multiple points per adm4_pcode.")

✅ GeoJSON successfully saved with these columns:
['adm4_pcode', 'location_adm4_en', 'date_y', 'pop_count_total', 'adm4_en', 'brgy_total_area_y', 'longitude', 'latitude', 'risk_level', 'risk_label', 'geometry']
Total barangays exported: 179