## KLIMATA ILOILO DATABASE CREATION

### After the standardization, we created also created another SQL database for the standardized datasets to store, organize, and efficiently manage multiple related tables so they can be easily queried, linked, and updated during machine learning.

In [6]:
import os
import sqlite3
import pandas as pd

# Folder where your CSV files are stored
folder_path = r"C:\Users\Value Lines\Documents\STANDARDIZED_DATASETS"

#  Create or connect to a local SQLite database
conn = sqlite3.connect("stand_datasets.db")
cursor = conn.cursor()

# oop through all CSV files in the folder
for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)

        # Use file name (without extension) as table name
        table_name = os.path.splitext(file)[0]

        # Save DataFrame as a SQL table
        df.to_sql(table_name, conn, if_exists="replace", index=False)
        print(f" Saved {table_name} to database")

conn = sqlite3.connect("stand_datasets.db")
cursor = conn.cursor()

# Confirm saved tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("\nðŸ“‹ Tables in database:")
for t in tables:
    print("-", t[0])

# Close the connection
conn.close()
print("\n Database created successfully: final_datasets.db")

âœ… Saved AMENITY_STANDARDIZED to database
âœ… Saved CLIMATE_STANDARDIZED to database
âœ… Saved HEALTH_STANDARDIZED to database
âœ… Saved POP_STANDARDIZED to database
âœ… Saved RWI_STANDARDIZED to database

ðŸ“‹ Tables in database:
- AMENITY_STANDARDIZED
- CLIMATE_STANDARDIZED
- HEALTH_STANDARDIZED
- POP_STANDARDIZED
- RWI_STANDARDIZED

âœ… Database created successfully: final_datasets.db

In [8]:
# Check if tables is a DataFrame or list

conn = sqlite3.connect("stand_datasets.db")

if isinstance(tables, pd.DataFrame):
    table_names = tables['name'].tolist()
else:
    table_names = [t[0] for t in tables]  # if it's a list of tuples

# Loop through and preview first 5 rows of each table
for table in table_names:
    print(f"\nðŸ“„ First 5 rows of table: {table}")
    preview = pd.read_sql(f"SELECT * FROM {table} LIMIT 5;", conn)
    print(preview)
    
conn.close()

ðŸ“„ First 5 rows of table: AMENITY_STANDARDIZED
          uuid   adm4_pcode        date  college_nearest  \
0  osmpa001e83  ph063022075  2022-01-01        -0.671659
1  osmpa001cac  ph063022085  2022-01-01        -0.907662
2  osmpa001cab  ph063022132  2022-01-01        -0.862404
3  osmpa001caa  ph063022092  2022-01-01        -0.629517
4  osmpa001ca9  ph063022054  2022-01-01        -1.044080

   community_centre_nearest  school_nearest  shelter_nearest  \
0                 -0.745288       -0.042481        -1.108379
1                 -0.771310       -0.743222        -0.862537
2                 -0.674097        0.013941        -0.968495
3                 -0.674470        0.106331        -0.578905
4                 -0.756960       -0.743222        -1.108413

   town_hall_nearest  university_nearest             location1.adm4_en  \
0          -0.997424           -0.802596  delgado-jalandoni-bagumbayan
1          -0.528983           -0.885474                        laguda
2          -0.926467           -0.278095                progreso-lapuz
3          -0.997424           -0.113042                libertad-lapuz
4          -0.720741           -0.401612                      edganzon

   location1.brgy_total_area
0                     0.0235
1                     0.0537
2                     0.2741
3                     0.0383
4                     0.1033

ðŸ“„ First 5 rows of table: CLIMATE_STANDARDIZED
    adm4_pcode        date      ndvi         uuid       no2        co  \
0  ph063022001  2003-01-01  0.160037  cairq61f770 -0.547791  0.811436
1  ph063022001  2003-01-02  0.281269  cairq0d5fc0 -1.448521  1.447295
2  ph063022001  2003-01-03 -0.203659  cairq0d5fc1 -1.136022  1.273270
3  ph063022001  2003-01-04  0.281269  cairq0d5fc2 -1.466903  0.911834
4  ph063022001  2003-01-05 -0.203659  cairq0d5fc3 -1.558814  0.925221

        so2        o3      pm10      pm25  heat_index        pr     adm4_en  \
0 -0.342429  0.159029  0.262435  0.234337   -0.825045 -0.025823  santa cruz
1 -0.802255  1.018687  0.848446  0.287189   -1.832101 -0.587649  santa cruz
2 -0.648980  0.984377  0.104007 -0.200487   -1.635725 -0.587649  santa cruz
3 -0.725617  0.959598  0.248806 -0.070760   -1.348714 -0.587649  santa cruz
4 -0.610661  0.713709 -0.265657 -0.580058   -1.630689 -0.587649  santa cruz

   brgy_total_area
0           0.5633
1           0.5633
2           0.5633
3           0.5633
4           0.5633

ðŸ“„ First 5 rows of table: HEALTH_STANDARDIZED
          uuid   adm4_pcode        date  \
0  mbiso000078  ph063022001  2022-01-01
1  mbiso000079  ph063022003  2022-01-01
2  mbiso00007a  ph063022004  2022-01-01
3  mbiso00007b  ph063022005  2022-01-01
4  mbiso00007c  ph063022006  2022-01-01

   brgy_healthcenter_pop_reached_pct_5min  \
0                                0.562868
1                               -1.606953
2                               -0.162319
3                                0.525556
4                               -0.257512

   brgy_healthcenter_pop_reached_pct_15min  \
0                                 0.497243
1                                -1.738661
2                                 0.409995
3                                 0.458795
4                                -0.348122

   brgy_healthcenter_pop_reached_pct_30min  hospital_pop_reached_pct_5min  \
0                                 0.492864                      -1.105819
1                                -1.741899                      -1.105819
2                                 0.405661                       0.671600
3                                 0.454436                      -1.105819
4                                -0.352069                      -0.854543

   hospital_pop_reached_pct_15min  hospital_pop_reached_pct_30min  \
0                        0.512752                        0.492864
1                       -1.707214                       -1.741899
2                        0.428481                        0.405661
3                        0.476986                        0.454436
4                       -0.325063                       -0.352069

   rhu_pop_reached_pct_5min  rhu_pop_reached_pct_15min  \
0                  0.576294                   0.533399
1                  0.009222                  -1.304870
2                  0.452001                   0.461668
3                  1.072750                   0.501789
4                  0.419556                  -0.161625

   rhu_pop_reached_pct_30min                    adm4_en  brgy_total_area
0                   0.493900                 santa cruz           0.5633
1                  -1.741662                  aguinaldo           0.0652
2                   0.406666  airport (tabucan airport)           1.0117
3                   0.455458             alalasan lapuz           0.0729
4                  -0.351336                  arguelles           0.1224

ðŸ“„ First 5 rows of table: POP_STANDARDIZED
          uuid   adm4_pcode        date  pop_count_total  pop_count_mean  \
0  wdpop000001  ph063022152  2000-01-01        -0.395875       -0.765972
1  wdpop000002  ph063022015  2000-01-01        -0.823156       -0.526084
2  wdpop000003  ph063022118  2000-01-01        -0.266876        0.140238
3  wdpop000018  ph063022040  2000-01-01        -0.183642       -0.410894
4  wdpop000019  ph063022020  2000-01-01        -0.116117        1.318897

   pop_count_median  pop_count_stdev  pop_count_min  pop_count_max  \
0         -0.707411        -0.515124      -0.639011      -0.691508
1         -0.458363        -0.550435      -0.267257      -0.631914
2         -0.671697         2.331493      -0.512312       2.829195
3         -0.355455        -0.298086      -0.432964      -0.353342
4          1.238063         0.858140       0.995730       0.947173

              adm4_en  brgy_total_area
0      hibao-an norte           0.8800
1              bantud           0.1261
2      north baluarte           0.1259
3            cuartero           0.2656
4  monica blumentritt           0.0626

ðŸ“„ First 5 rows of table: RWI_STANDARDIZED
          uuid   adm4_pcode        date   rwi_max  rwi_mean  rwi_median  \
0  tmrwi000002  ph063022043  2016-01-01 -0.752518 -0.593147   -0.482518
1  tmrwi000006  ph063022042  2016-01-01 -1.897069 -1.784427   -1.829337
2  tmrwi000008  ph063022041  2016-01-01  0.422886  0.168145    0.202362
3  tmrwi00000c  ph063022040  2016-01-01 -1.310030 -1.353632   -1.347036
4  tmrwi00000e  ph063022038  2016-01-01 -0.311894 -0.298192   -0.371389

    rwi_min   rwi_std            adm4_en  brgy_total_area
0 -0.443668 -0.435557     mabolo-delgado           0.0524
1 -1.281248 -1.047442              danao           0.1989
2 -0.590055  0.397060              cubay           1.0505
3 -1.178499 -0.040366           cuartero           0.2656
4 -0.099049 -0.501858  concepcion-montes           0.2205